services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
    ports:
      - 9092:9092

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: notifications_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  api:
    build:
        context: .
        dockerfile: Dockerfile
        args:
            mode: api
    volumes:
        - $HOME/.aws:/root/.aws:ro
    ports:
        - '3000:3000'
    healthcheck:
        test: ['CMD', 'curl', '-k', '-f', 'http://localhost:3000/health']
        interval: 5s
        timeout: 5s
        retries: 1
        start_period: 10s
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/notifications_db
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKERS=kafka:9092
      - OUTBOX_INLINE_PUBLISHER=false

  outbox-publisher:
    build: .
    depends_on:
      - postgres
      - kafka
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/notifications_db
      - KAFKA_BROKERS=kafka:9092
    command: sh -c "npm run outbox-publisher"

  worker:
    build: .
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      - NODE_ENV=development
      - KAFKA_BROKERS=kafka:9092
      - REDIS_URL=redis://redis:6379
      - KAFKA_SUBSCRIBE_TOPICS=notifications.high,notifications.low
    command: sh -c "npm run start-consumer"
    restart: unless-stopped

  worker-high:
    build: .
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      - NODE_ENV=development
      - KAFKA_BROKERS=kafka:9092
      - REDIS_URL=redis://redis:6379
      - CONSUMER_GROUP=blunav-worker-high
      - KAFKA_SUBSCRIBE_TOPICS=notifications.high
    command: sh -c "npm run start-consumer"

  worker-low:
    build: .
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      - NODE_ENV=development
      - KAFKA_BROKERS=kafka:9092
      - REDIS_URL=redis://redis:6379
      - CONSUMER_GROUP=blunav-worker-low
      - KAFKA_SUBSCRIBE_TOPICS=notifications.low
    command: sh -c "npm run start-consumer"

volumes:
  pgdata:

networks:
    blunav-network:
        driver: bridge
